title: 팩트시트
description: 대한민국 정부 및 각 기관 부처 홈페이지, 지역의 정신건강복지센터, 복지관, WHO 등 신뢰성있는 기관에서 가져온 정보로만 정리했습니다.
theme: just-the-docs

url: https://serieslearner.github.io

callouts:
  red-callout:
    title: 미리 휴대폰에 저장해 두세요
    color: red
  yellow-callout:
    color: yellow
  green-callout:
    title: 업데이트 일자 2024.09.19
    color: green